services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: 'BfZTbHC0u7Np'
      POSTGRES_USER: crypto_owner
      POSTGRES_DB: crypto
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  cache:
    image: redis:7.0.3-alpine
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass password

volumes:
  dbdata:
    driver: local
  cache:
    driver: local